const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const FORBIDDEN = 403;
const SERVER_ERROR = 500;
const UNAUTHORIZED = 401
const CONFLICT = 409


module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  SERVER_ERROR,
  FORBIDDEN,
  UNAUTHORIZED,
  CONFLICT
};
